CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  nombres TEXT NOT NULL,
  apellidos TEXT NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  nombre_completo TEXT GENERATED ALWAYS AS (nombres || ' ' || apellidos) STORED,
  grupos TEXT[] NOT NULL DEFAULT ARRAY['user']::TEXT[],
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT usuarios_grupos_ck CHECK (grupos <@ ARRAY['user','admin','superadmin']::TEXT[])
);

CREATE TABLE IF NOT EXISTS credenciales (
  id_usuario INTEGER PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tareas (
  id_tarea INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_creador INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  grupo TEXT NOT NULL,
  titulo TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  prioridad TEXT NOT NULL DEFAULT '1:media',
  creada TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  terminada TIMESTAMPTZ NULL
);
